---
- name: Setup Mac OS Workspace
  hosts: localhost
  connection: local
  # gather_facts: false
  vars:
    node_version: "24"
    # Default to Intel path
    fish_shell_path: /usr/local/bin/fish
  tasks:
    - name: Ensure Homebrew is installed
      homebrew:
        name: brew
        state: present
      tags:
        - homebrew
        - setup

    # Import modular tasks
    - name: Include Node.js and Bun setup
      include_tasks: mac-module/node.yml
      tags: [node, volta, bun, pnpm]

    - name: Include GUI applications
      include_tasks: mac-module/apps.yml
      tags: [apps, fork]

    - name: Include AI tools
      include_tasks: mac-module/ai.yml
      tags: [ai]

    - name: Include shell configuration
      include_tasks: mac-module/shell.yml
      tags: [shell]

    - name: Include fonts
      include_tasks: mac-module/fonts.yml
      tags: [fonts]

    - name: Include CLI tools
      include_tasks: mac-module/cli.yml
      tags: [cli, neovim, astronvim]

    - name: Include Python tools
      include_tasks: mac-module/python.yml
      tags: [python]