---
- name: Setup Mac OS Workspace
  hosts: localhost
  vars:
    - whoami: haiczhan

  pre_tasks:
    - name: Update Mac Permissions
      become: yes
      shell: chown -R {{ whoami }} /usr/local/bin /usr/local/lib /usr/local/include /usr/local/share

  tasks:
    - include: mac-module/app.yml
    - include: mac-module/terminal.yml
    - include: mac-module/node.yml
      
