---
- name: Setup Mac OS Workspace
  hosts: localhost
  connection: local
  # gather_facts: false
  vars:
    node_version: "24"
    # Default to Intel path
    fish_shell_path: /usr/local/bin/fish
  tasks:
    # Import modular tasks
    - name: Include js, Node.js and Bun setup
      include_tasks: mac-module/js.yml
      tags: [js]

    - name: Include GUI applications
      include_tasks: mac-module/app.yml
      tags: [app]

    - name: Include AI tools
      include_tasks: mac-module/ai.yml
      tags: [ai]

    - name: Include shell configuration
      include_tasks: mac-module/shell.yml
      tags: [shell]

    - name: Include fonts
      include_tasks: mac-module/font.yml
      tags: [font]

    - name: Include CLI tools
      include_tasks: mac-module/cli.yml
      tags: [cli]

    - name: Include Python tools
      include_tasks: mac-module/python.yml
      tags: [python]

    - name: Include Java development tools
      include_tasks: mac-module/java.yml
      tags: [java]