---
- name: Setup Mac OS Workspace
  hosts: localhost

  tasks:
    - name: Install iTerm2
      community.general.homebrew_cask:
        name: iterm2
        state: present
      tags: [app]
    - name: Install Zsh
      community.general.homebrew:
        name: zsh
        state: latest
      tags: [terminal]
    - name: Install oh-my-zsh
      shell: "sh -c $(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
      tags: [terminal]
    - name: Install Zsh plugin - auto suggestions
      ansible.builtin.git:
        repo: "https://github.com/zsh-users/zsh-autosuggestions"
        dest: ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
        version: main
      tags: [terminal]
    - name: Install node version management n
      community.general.homebrew:
        name: n
        state: latest
      tags: [js, node]
