---
# GUI Applications

- name: Install iTerm2
  homebrew_cask:
    name: iterm2
    state: present
  tags: [app-all, iterm2]

- name: Install VS Code
  homebrew_cask:
    name: visual-studio-code
    state: present
  tags: [app-all, vscode]

- name: Install AltTab and Rectangle
  homebrew_cask:
    name:
      - alt-tab
      - rectangle
    state: present
  tags:
    - app-all
    - alttab
    - rectangle

- name: Install Fork Git client
  homebrew_cask:
    name: fork
    state: present
  tags: [app-all, fork, git]

- name: Install Postman
  homebrew_cask:
    name: postman
    state: present
  tags: [app-all, postman, api]

- name: Install VNC Viewer
  homebrew_cask:
    name: vnc-viewer
    state: present
  tags: [app-all, vnc]

- name: Install Notion
  homebrew_cask:
    name: notion
    state: present
  tags: [app-all, notion]

- name: Install Rancher Desktop
  homebrew_cask:
    name: rancher
    state: present
  tags: [app-all, rancher, docker, kubernetes]