#!/bin/sh

folders=(
    "/scratch/helium/helium.js"
    "/scratch/helium/helium-label.purs"
    "/scratch/helium/helium-adhoc.ts"
    "/scratch/helium/environments"
)

session=$(echo "${folders[*]}" | tr ' ' '\n' | fzf)

if [[ -z $session ]]; then
    exit 0
fi

session_name=$(basename "$session" | tr . '_')

#echo ${session_name}
if [ ! tmux has-session -t "$session_name" 2> /dev/null ]; then
    tmux new-session -s "$session_name" -c "$session" -d
fi


tmux switch-client -t "$session_name"
