#!/bin/sh

language=$(echo "golang js nodejs typescript purescript haskell" | tr " " "\n")
core_utils=$(echo "find xargs sed awk" | tr " " "\n")
selected=$(echo "$language\n$core_utils" | fzf)


read -p "?: " query

if echo "$languages" | grep -qs $selected; then
    curl cht.sh/$selected/$(echo "$query" | tr " " "+")   
else
    curl cht.sh/$selected-$query
fi

