#!/bin/sh

manual_list=(
    "${HOME}/.dotfile"
    "/scratch/helium/helium.js"
    "/scratch/helium/helium-label.purs"
    "/scratch/helium/helium-adhoc.ts"
    "/scratch/helium/environments"
)

find_list=( $(find ~/Workspace -maxdepth 1 -mindepth 1 -type d) )

list=(${manual_list[@]} ${find_list[@]})
folders=()

for f in "${list[@]}"
do
    if [[ -d "${f}" ]]
    then
        folders+=("${f}")
    fi
done

session=$(echo "${folders[*]}" | tr ' ' '\n' | fzf)

if [[ -z $session ]]; then
    exit 0
fi

session_name=$(basename "$session" | tr . '_')

if ! tmux has-session -t "$session_name" ; then
    echo "Create session $session_name"
    tmux new-session -s "$session_name" -c "$session" -d
fi

if [ -z "${TMUX}" ]; then
    tmux attach -t $session_name
else
    tmux switch-client -t "$session_name"
fi

