#!/bin/sh

manual_list=(
    "${HOME}/.dotfile"
    "/scratch/helium/helium.js"
    "/scratch/helium/helium-label.purs"
    "/scratch/helium/helium-adhoc.ts"
    "/scratch/helium/environments"
)

image_folders=( $(find /scratch/helium/helium.js/images -maxdepth 1 -mindepth 1 -type d) )

find_list=( $(find ~/Workspace -maxdepth 2 -mindepth 1 -type d) )

list=(${manual_list[@]} ${find_list[@]})
folders=()

for f in "${list[@]}"
do
    if [[ -d "${f}" ]]
    then
        folders+=("${f}")
    fi
done

session=$(echo "${folders[*]}" | tr ' ' '\n' | fzf)

if [[ -z $session ]]; then
    exit 0
fi

session_name=$(basename "$session" | tr . '_')

tmux has-session -t "$session_name"

if [ $? != 0 ]; then
    echo "Create session $session_name"
    tmux new-session -s $session_name -d
    tmux send-keys -t $session_name "cd $session" C-m
    tmux send-keys -t $session_name "vi ." C-m
    # tmux split-window -v -t $session_name
    # tmux select-layout -t $session_name main-horizontal
    tmux split-window -v -p 15 -t $session_name
    tmux send-keys -t $session_name:1.2 "cd $session" C-m
    tmux new-window -n console -t $session_name
    tmux send-keys -t $session_name:2 "cd $session" C-m
    tmux select-window -t $session_name:1
    tmux select-pane -t $session_name:1.1
fi

if [ -z "${TMUX}" ]; then
    tmux attach -t $session_name
else
    tmux switch-client -t "$session_name"
fi

